{
  "api": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  },
  "core.player_initializer": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  },
  "entrypoints.run_web_ui_optimized": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  },
  "main_menu": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  },
  "routes.character": {
    "error": "ImportError",
    "message": "cannot import name 'CommunityHub' from 'xwe.features.community_system' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/features/community_system.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/features/__init__.py\", line 32, in <module>",
      "    from xwe.features.community_system import (",
      "ImportError: cannot import name 'CommunityHub' from 'xwe.features.community_system' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/features/community_system.py)"
    ]
  },
  "xwe.core": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  },
  "xwe.engine.expression": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  },
  "xwe.features": {
    "error": "ImportError",
    "message": "cannot import name 'CommunityHub' from 'xwe.features.community_system' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/features/community_system.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/features/__init__.py\", line 32, in <module>",
      "    from xwe.features.community_system import (",
      "ImportError: cannot import name 'CommunityHub' from 'xwe.features.community_system' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/features/community_system.py)"
    ]
  },
  "xwe.metrics": {
    "error": "ImportError",
    "message": "cannot import name 'metrics_registry' from 'xwe.metrics.prometheus' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/metrics/prometheus/__init__.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/metrics/__init__.py\", line 5, in <module>",
      "    from .prometheus import (",
      "ImportError: cannot import name 'metrics_registry' from 'xwe.metrics.prometheus' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/metrics/prometheus/__init__.py)"
    ]
  },
  "xwe.services": {
    "error": "ImportError",
    "message": "cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)",
    "trace": [
      "  File \"/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/__init__.py\", line 19, in <module>",
      "    from .exceptions import (",
      "ImportError: cannot import name 'ValidationError' from 'xwe.engine.expression.exceptions' (/Users/chenpinle/Desktop/杂/pythonProject/xianxia_world_engine/xwe/engine/expression/exceptions.py)"
    ]
  }
}